create table USER
(
	USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   	NAME VARCHAR(100) NOT NULL,
   	LOGIN_ID VARCHAR(100) NOT NULL,
   	PASSWORD VARCHAR(100) NOT NULL,
   	PRIMARY KEY (USER_ID)
);


create table SOFT_SKILL
(
	SKILL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
   	NAME VARCHAR(100) NOT NULL,  
   	PRIMARY KEY (SKILL_ID)
);


create table USER_SKILL_RATING
(
	USER_ID INT UNSIGNED NOT NULL,
	SKILL_ID INT UNSIGNED NOT NULL,
	RATING INT UNSIGNED NOT NULL,
	PRIMARY KEY (USER_ID, SKILL_ID)
);


ALTER TABLE USER_SKILL_RATING ADD CONSTRAINT FK_USR_USER_ID FOREIGN KEY
(
   USER_ID
)
REFERENCES USER (USER_ID) ON DELETE CASCADE;

ALTER TABLE USER_SKILL_RATING ADD CONSTRAINT FK_USR_SKILL_ID FOREIGN KEY
(
   SKILL_ID
)
REFERENCES SOFT_SKILL (SKILL_ID);
